version: '3.4'

services:
  urlshortenerapp:
    image: url-shortener-app:1.0
    ports:
      - 3000:3000
  mysql-url-shortener:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - ~/personal/mysql-data:/var/lib/mysql
  redis-url-shortener:
    image: redis:alpine
    ports:
      - 6379:6379

