apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-app
  template:
    metadata:
      labels:
        app: url-shortener-app
    spec:
      containers:
      - name: url-shortener-app
        image: url-shortener-app:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-app
spec:
  selector:
    app: url-shortener-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
