apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-url-shortener
spec:
  selector:
    matchLabels:
      app: redis-url-shortener
  template:
    metadata:
      labels:
        app: redis-url-shortener
    spec:
      containers:
      - name: redis-url-shortener
        image: redis:alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-url-shortener
spec:
  selector:
    app: redis-url-shortener
  ports:
    - port: 6379
      targetPort: 6379